export {
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  BoldIcon,
  ColorFillIcon,
  ColorTextIcon,
  ImageIcon,
  IndentDecreaseIcon,
  IndentIncreaseIcon,
  ItalicIcon,
  LinkIcon,
  ListBulletedIcon,
  ListNumberedIcon,
  RedoIcon,
  StrikethroughIcon,
  TableIcon,
  UnderlinedIcon,
  UndoIcon,
} from "./Icons";
